name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      # Matrix内で失敗したジョブがあっても実行させる。
      fail-fast: false
      matrix:
        compiler: [cl, g++, clang++]
        build_type: [debug, release]
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Restore artifacts, or setup vcpkg (do not install any package)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      - name: Configure CMake
        run: |
          cmake --preset windows-${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
      - name: Build
        run: |
          cmake --build --preset windows-${{ matrix.build_type }}
