name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      # Matrix内で失敗したジョブがあっても実行させる。
      fail-fast: false
      matrix:
        compiler: [cl, g++, clang++]
        build_type: [debug, release]
    env:
      VCPKG_ROOT: ${{ github.workspace }}/BuildTools/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/BuildTools/vcpkg/bincache
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: "Create directory '${{ env.VCPKG_DEFAULT_BINARY_CACHE }}'"
        run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
        shell: bash
      - uses: lukka/get-cmake@latest
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Configure CMake
        run: |
          cmake --preset windows-${{ matrix.build_type }} -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
      - name: Build
        run: |
          cmake --build --preset windows-${{ matrix.build_type }}
